=== olerabanal/ESAS-genererte-kontrakter/publish_kontrakter/kontrakter/kriminalomsorg/avvisningTilbudtVaretektsplass/avvisningTilbudtVaretektsplass.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://kriminalomsorgen.no/kriminalomsorg/fengsling/1.0/avvisningTilbudtVaretektsplass",
  "description": "Avvisning av tilbud om varetektsplass fra påtale til KO. Schema versjon 2020-12",
  "type": "object",
  "properties": {
    "melding": {
      "type": "string",
      "const": "AVVISNING_TILBUDT_VARETEKTSPLASS",
      "description": "Navnet på meldingen. Enkelt å se på en melding hvilken type det er."
    },
    "forsendelse": {
      "$ref": "#/definitions/forsendelse",
      "description": "avsender og mottaker"
    },
    "hovedStraffesaksnummer": {
      "$ref": "#/definitions/straffesaksnummer",
      "description": "BL Saksbehandlersak er hovedsaken i et sakskompleks (som er 1 eller flere straffesaker)"
    },
    "avvisningTilbudtVaretektsplassId": {
      "$ref": "#/definitions/unikId",
      "description": "ID på denne avvisningen av plasstilbudet. "
    },
    "avvisningsgrunn": {
      "type": "string",
      "description": "En forklaring på hvorfor politiet ikke ønsker benytte tilbudt plass. Fritekst i første versjon. Kan lages en enum type VaretektIkkeLengerAktuelt, TransportTilPlassAnseesForTidkrevende etc. ... nyttig for statistikk, men dette er ikke kritisk viktig og kan tas i en senere versjon."
    },
    "tilbudVaretektsplassId": {
      "$ref": "#/definitions/unikId",
      "description": "ID på plasstilbudet. Denne meldingen er et  svar på tilbudet og  skal kobles til denne  nøkkelen."
    },
    "bestillingAvVaretektsplassId": {
      "$ref": "#/definitions/unikId",
      "description": "Nøkkel på bestillingen. Denne meldingen er en oppfølging av  bestilling og må referere til denne bestillingsID-en."
    },
    "kontaktPersonKDI": { "$ref": "#/definitions/ansattPerson" },
    "varetektSyklusId": {
      "$ref": "#/definitions/unikId",
      "description": "Til å begynne med vil dette være et løpenummer, kan endres til GUID senere. Første forsendelsene vil ikke inneholde dette."
    },
    "fengselDerPlassTilbys": { "$ref": "#/definitions/organisasjon" },
    "dokumenter": {
      "type": "array",
      "items": { "$ref": "#/definitions/dokument" }
    }
  },
  "required": [
    "melding",
    "forsendelse",
    "hovedStraffesaksnummer",
    "bestillingAvVaretektsplassId",
    "tilbudVaretektsplassId",
    "avvisningTilbudtVaretektsplassId"
  ],
  "additionalProperties": false,

  "definitions": {
    "ansattPerson": {
      "type": "object",
      "description": "Saksbehandler, jurist etterforsker hos politiet, ansatte hos domstolene eller kriminalomsorgen",
      "properties": {
        "brukeridentifikasjon": {
          "type": "string",
          "description": "Id som ikke endrer seg, vil være BID hos politiet til å begynne med, men vil endres"
        },
        "tittel": {
          "type": "string"
        },
        "fornavn": {
          "type": "string"
        },
        "mellomnavn": {
          "type": "string"
        },
        "etternavn": {
          "type": "string"
        },
        "kontakt": {
          "$ref": "#/definitions/kontaktInfo",
          "description": "Er ikke med i første fase, burde inneholde kontaktinformasjon på forsendelsen."
        }
      },
      "required": ["etternavn"],
      "additionalProperties": false
    },
    "avsender": {
      "type": "object",
      "properties": {
        "organisasjon": {
          "$ref": "#/definitions/organisasjon"
        },
        "person": {
          "$ref": "#/definitions/ansattPerson",
          "description": "Person som trykker på send til domstolen."
        }
      },
      "required": ["organisasjon"],
      "additionalProperties": false
    },
    "kontaktInfo": {
      "type": "object",
      "properties": {
        "epost": {
          "type": "string"
        },
        "telefonnummer": {
          "type": "array",
          "items": { "$ref": "#/definitions/telefonnummer" }
        }
      },
      "required": ["telefonnummer"],
      "additionalProperties": false
    },
    "dokument": {
      "description": "Dokument som oversendes på justishub",
      "type": "object",
      "properties": {
        "internId": { "type": "string" },
        "kategori": { "$ref": "#/definitions/kodeverk" },
        "overskrift": { "type": "string" },
        "skrevetDato": {
          "description": "Dato",
          "type": "string",
          "format": "date-time"
        },
        "forsendelse": { "$ref": "#/definitions/dokumentForsendelse" }
      },
      "required": ["overskrift", "forsendelse"],
      "additionalProperties": false
    },
    "dokumentForsendelse": {
      "description": "Detaljer om lokasjon og type",
      "type": "object",
      "properties": {
        "mimeType": { "type": "string" },
        "uri": { "type": "string" },
        "sjekksum": { "type": "string" }
      },
      "required": ["mimeType", "uri", "sjekksum"],
      "additionalProperties": false
    },
    "forsendelse": {
      "type": "object",
      "description": "Sender (kriminalomsorg) og mottaker (påtale) av meldingen",
      "properties": {
        "meldingsId": {
          "type": "string"
        },
        "sendtTid": {
          "type": "string",
          "format": "date-time"
        },
        "avsender": {
          "$ref": "#/definitions/avsender"
        },
        "mottakerOrganisasjon": {
          "$ref": "#/definitions/organisasjon",
          "description": "Bestillende politidistrikt."
        }
      },
      "required": [
        "meldingsId",
        "avsender",
        "mottakerOrganisasjon",
        "sendtTid"
      ],
      "additionalProperties": false
    },
    "organisasjon": {
      "description": "Entydig identifikator av juridisk enhet. F.eks en spesifik domstol, embete eller politidistrikt",
      "type": "object",
      "properties": {
        "navn": {
          "description": "F.eks. Oslo politidistikt, Riksadvokaten, Borgarting lagmannsrett",
          "type": "string"
        },
        "organisasjonsnummer": {
          "$ref": "#/definitions/organisasjonsnummer"
        }
      },
      "required": ["organisasjonsnummer", "navn"],
      "additionalProperties": false
    },
    "personnavn": {
      "type": "object",
      "properties": {
        "fornavn": { "type": "string" },
        "mellomnavn": { "type": "string" },
        "etternavn": { "type": "string" }
      },
      "required": ["etternavn"],
      "additionalProperties": false
    },
    "kodeverk": {
      "description": "Kode og navn, kommer oppdatering med verdier",
      "type": "object",
      "properties": {
        "kode": { "type": "string" },
        "navn": { "type": "string" }
      },
      "required": ["kode"],
      "additionalProperties": false
    },
    "organisasjonsnummer": {
      "type": "string",
      "description": "Norsk organisasjonsnummer fra BRREG. Referanse til politistrikt, domstol, fengsel. https://www.brreg.no/om-oss/registrene-vare/om-enhetsregisteret/organisasjonsnummeret/",
      "pattern": "[0-9]+",
      "minLength": 9,
      "maxLength": 9
    },
    "straffesaksnummer": {
      "type": "string",
      "description": "Som regel et løpenummer, men kan i fremtiden også inneholde bokstaver",
      "minLength": 3,
      "maxLength": 30
    },
    "telefonnummer": {
      "type": "string",
      "description": "Ett telefonnummer, norsk eller utenlands, med eller uten land prefix",
      "maxLength": 30,
      "minLength": 1
    },
    "unikId": {
      "type": "string",
      "description": "GUID eller andre unike id'er. Trenger ikke være global unik.",
      "maxLength": 40,
      "minLength": 1
    }
  }
}

=== olerabanal/ESAS-genererte-kontrakter/publish_kontrakter/kontrakter/kriminalomsorg/avvisningTilbudtVaretektsplass/eksempelfiler/avvisningTilbudtVaretektsplass.eksempel-1.json
{
  "melding": "AVVISNING_TILBUDT_VARETEKTSPLASS",
  "forsendelse": {
    "meldingsId": "C5E8E429-2B8E-48A9-A9D3-FDAA5F9BEZ",
    "sendtTid": "2022-11-03T10:19:55+02:00",
    "avsender": {
      "organisasjon": {
        "organisasjonsnummer": "983997953",
        "navn": "Innlandet politidistrikt"
      },
      "person": {
        "brukeridentifikasjon": "PITBID123",
        "etternavn": "PITBrukersen"
      }
    },
    "mottakerOrganisasjon": {
      "organisasjonsnummer": "911830868",
      "navn": "Kriminalomsorgsdirektoratet"
    }
  },
  "avvisningTilbudtVaretektsplassId": "8e0f4c4b-97d7-49e8-9051-1fb92b88b9ab",
  "avvisningsgrunn": "Annen person nå pågrepet og siktet.",
  "tilbudVaretektsplassId": "b04782d3-502e-43d8-8c45-7e84d279d33a",
  "hovedStraffesaksnummer": "15434811",
  "varetektSyklusId": "D784D27C-C1BB-4BB2-90FD-96C414A64AE1",
  "bestillingAvVaretektsplassId": "0322B3E2-B12B-40B6-8940-799C48706BE2",
  "kontaktPersonKDI": {
    "fornavn": "Peder",
    "etternavn": "Superduper"
  },
  "fengselDerPlassTilbys": {
    "organisasjonsnummer": "890286712",
    "navn": "Bjørgvin fengsel"
  }
}
