=== olerabanal/ESAS-genererte-kontrakter/publish_kontrakter/kontrakter/personundersoekelse/returPersonundersoekelse/returPersonundersoekelse.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://kriminalomsorg.no/kriminalomsorg/1.0/returPersonundersoekelse",
  "description": "Retur som svarer ut en rekvirert personundersøkelse. Inneholder normalt den ferdige PeU-rapporten (PDF). Sendes fra kriminalomsorgen til politiet. Schema versjon 2020-12",
  "type": "object",
  "properties": {
    "forsendelse": {
      "$ref": "#/definitions/forsendelse",
      "description": "avsender og mottaker"
    },
    "hovedStraffesaksnummer": {
      "$ref": "#/definitions/straffesaksnummer",
      "description": "BL Saksbehandlersak er hovedsaken i et sakskompleks (som er 1 eller flere straffesaker)"
    },
    "rekvisisjonPersonundersoekelseId": {
      "$ref": "#/definitions/unikId",
      "description": "ID  på den tidligere rekvisisjonen kriminalomsorgen nå svarer ut. "
    },
    "returPersonundersoekelseId": {
      "$ref": "#/definitions/unikId",
      "description": "ID  på returen. "
    },
    "dokumenter": {
      "type": "array",
      "items": { "$ref": "#/definitions/dokument" }
    }
  },
  "required": [
    "forsendelse",
    "hovedStraffesaksnummer",
    "rekvisisjonPersonundersoekelseId",
    "returPersonundersoekelseId",
    "dokumenter"
  ],
  "additionalProperties": false,

  "definitions": {
    "ansattPerson": {
      "type": "object",
      "description": "Saksbehandler, jurist etterforsker hos politiet, ansatte hos domstolene eller kriminalomsorgen",
      "properties": {
        "brukeridentifikasjon": {
          "type": "string",
          "description": "Id som ikke endrer seg, vil være BID hos politiet til å begynne med, men vil endres"
        },
        "tittel": {
          "type": "string"
        },
        "fornavn": {
          "type": "string"
        },
        "mellomnavn": {
          "type": "string"
        },
        "etternavn": {
          "type": "string"
        },
        "kontakt": {
          "$ref": "#/definitions/kontaktInfo",
          "description": "Kontaktinformasjon på forsendelsen."
        }
      },
      "required": ["etternavn", "kontakt"],
      "additionalProperties": false
    },
    "avsender": {
      "type": "object",
      "properties": {
        "organisasjon": {
          "$ref": "#/definitions/organisasjon"
        },
        "person": {
          "$ref": "#/definitions/ansattPerson",
          "description": "Person som trykker på send til kriminalomsorgen."
        }
      },
      "required": ["organisasjon", "person"],
      "additionalProperties": false
    },
    "dokument": {
      "description": "Dokument som oversendes på justishub",
      "type": "object",
      "properties": {
        "internId": { "type": "string" },
        "kategori": { "$ref": "#/definitions/kodeverk" },
        "overskrift": { "type": "string" },
        "skrevetDato": {
          "description": "Dato",
          "type": "string",
          "format": "date-time"
        },
        "forsendelse": { "$ref": "#/definitions/dokumentForsendelse" }
      },
      "required": ["overskrift", "forsendelse"],
      "additionalProperties": false
    },
    "dokumentForsendelse": {
      "description": "Detaljer om lokasjon og type",
      "type": "object",
      "properties": {
        "mimeType": { "type": "string" },
        "uri": { "type": "string" },
        "sjekksum": { "type": "string" }
      },
      "required": ["mimeType", "uri", "sjekksum"],
      "additionalProperties": false
    },
    "forsendelse": {
      "type": "object",
      "description": "Sender (kriminalomsorg) og mottaker (påtale)  av meldingen",
      "properties": {
        "meldingsId": {
          "type": "string"
        },
        "sendtTid": {
          "type": "string",
          "format": "date-time"
        },
        "avsender": {
          "$ref": "#/definitions/avsender"
        },
        "mottakerOrganisasjon": {
          "$ref": "#/definitions/organisasjon",
          "description": "Returneres til rekvirerende enhet hos politiet. Politiet ruter videre internt basert på rekvisisjonsID."
        }
      },
      "required": [
        "meldingsId",
        "avsender",
        "mottakerOrganisasjon",
        "sendtTid"
      ],
      "additionalProperties": false
    },
    "kontaktInfo": {
      "type": "object",
      "properties": {
        "epost": {
          "type": "string"
        },
        "telefonnummer": {
          "type": "array",
          "items": { "$ref": "#/definitions/telefonnummer" }
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "personnavn": {
      "type": "object",
      "properties": {
        "fornavn": { "type": "string" },
        "mellomnavn": { "type": "string" },
        "etternavn": { "type": "string" }
      },
      "required": ["etternavn"],
      "additionalProperties": false
    },
    "kodeverk": {
      "description": "Kode og navn, kommer oppdatering med verdier",
      "type": "object",
      "properties": {
        "kode": { "type": "string" },
        "navn": { "type": "string" }
      },
      "required": ["kode"],
      "additionalProperties": false
    },
    "organisasjonsnummer": {
      "type": "string",
      "description": "Norsk organisasjonsnummer fra BRREG. Referanse til politistrikt, domstol, fengsel. https://www.brreg.no/om-oss/registrene-vare/om-enhetsregisteret/organisasjonsnummeret/",
      "pattern": "[0-9]+",
      "minLength": 9,
      "maxLength": 9
    },
    "organisasjon": {
      "description": "Entydig identifikator av juridisk enhet. F.eks en spesifik domstol, embete eller politidistrikt",
      "type": "object",
      "properties": {
        "navn": {
          "description": "F.eks. Oslo politidistikt, Riksadvokaten, Borgarting lagmannsrett",
          "type": "string"
        },
        "organisasjonsnummer": {
          "$ref": "#/definitions/organisasjonsnummer"
        }
      },
      "required": ["organisasjonsnummer", "navn"],
      "additionalProperties": false
    },
    "straffesaksnummer": {
      "type": "string",
      "description": "Som regel et løpenummer, men kan i fremtiden også inneholde bokstaver",
      "minLength": 3,
      "maxLength": 30
    },
    "telefonnummer": {
      "type": "string",
      "description": "Ett telefonnummer, norsk eller utenlands, med eller uten land prefix",
      "maxLength": 30,
      "minLength": 1
    },
    "unikId": {
      "type": "string",
      "description": "GUID eller andre unike id'er. Trenger ikke være global unik.",
      "maxLength": 40,
      "minLength": 1
    }
  }
}

=== olerabanal/ESAS-genererte-kontrakter/publish_kontrakter/kontrakter/personundersoekelse/returPersonundersoekelse/eksempelfiler/returPersonundersoekelse-eksempel-1.json
{
  "forsendelse": {
    "meldingsId": "C5E8E429-4321-48A9-A9D3-FDAA5F9BE2",
    "sendtTid": "2023-11-03T10:19:55+02:00",
    "avsender": {
      "organisasjon": {
        "organisasjonsnummer": "911830868",
        "navn": "Akershus friomsorgskontor"
      },
      "person": {
        "fornavn": "Per",
        "mellomnavn": "S.",
        "etternavn": "Undersøkersen",
        "kontakt": {
          "telefonnummer": ["22 11 33 44"],
          "epost": "epost@krimomsorg1.no"
        }
      }
    },
    "mottakerOrganisasjon": {
      "organisasjonsnummer": "983997953",
      "navn": "Innlandet politidistrikt"
    }
  },
  "hovedStraffesaksnummer": "15434811",
  "rekvisisjonPersonundersoekelseId": "0322B3E2-B12B-40B6-8940-799C48706123",
  "returPersonundersoekelseId": "0322B3E2-B12B-40B6-1234-799C48706123",
  "dokumenter": [
    {
      "internId": "123234567871",
      "overskrift": "Personundersøkelse(PDF)",
      "kategori": {
        "kode": "RETUR_PERSONUNDERSOEKELSE"
      },
      "skrevetDato": "2022-10-14T00:00:00+02:00",
      "forsendelse": {
        "mimeType": "application/pdf",
        "uri": "file:///asdfaasdfsdfu",
        "sjekksum": "234asass"
      }
    }
  ]
}
